                                    ***Sakib Mizan_A_2154901009 ML Final Project***

### Importing Libraries

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing Dataset

In [64]:
dataset = pd.read_csv('14-StudentsPerformance.csv')
dataset.head(20)

gender race/ethnicity parental level of education         lunch  \
0   female        group B           bachelor's degree      standard   
1   female        group C                some college      standard   
2   female        group B             master's degree      standard   
3     male        group A          associate's degree  free/reduced   
4     male        group C                some college      standard   
5   female        group B          associate's degree      standard   
6   female        group B                some college      standard   
7     male        group B                some college  free/reduced   
8     male        group D                 high school  free/reduced   
9   female        group B                 high school  free/reduced   
10    male        group C          associate's degree      standard   
11    male        group D          associate's degree      standard   
12  female        group B                 high school      standard   
13    male        group A                some college      standard   
14  female        group A             master's degree      standard   
15  female        group C            some high school      standard   
16    male        group C                 high school      standard   
17  female        group B            some high school  free/reduced   
18    male        group C             master's degree  free/reduced   
19  female        group C          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score  
0                     none          72             72             74  
1                completed          69             90             88  
2                     none          90             95             93  
3                     none          47             57             44  
4                     none          76             78             75  
5                     none          71             83             78  
6                completed          88             95             92  
7                     none          40             43             39  
8                completed          64             64             67  
9                     none          38             60             50  
10                    none          58             54             52  
11                    none          40             52             43  
12                    none          65             81             73  
13               completed          78             72             70  
14                    none          50             53             58  
15                    none          69             75             78  
16                    none          88             89             86  
17                    none          18             32             28  
18               completed          46             42             46  
19                    none          54             58             61

In [65]:
dataset.shape

(1000, 8)

### Check Dataset for Missing Values

In [66]:
missing_data = dataset.isnull().sum()
print(missing_data)

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64


### Checking for Duplicate Data

In [67]:
duplicate_data = dataset.duplicated().sum()
print(duplicate_data)

0


### Checking Data Type

In [68]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


### Checking for Unique Entities

In [69]:
dataset.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

### Statistical Overview of the Dataset

In [70]:
dataset.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Duplicating & Modifying Dataset to Analyze Student Performance

In [71]:
dataset_copy = dataset.copy()

### Adding Average Score & Pass/Fail Column to the Duplicate Dataset

In [72]:
#dataset_copy["average score"] = dataset_copy[["math score", "reading score", "writing score"]].mean(axis = 1)
dataset_copy["pass/fail"] = dataset_copy.apply(lambda row: "Yes" if row["math score"] >= 40 and row["reading score"] >= 40 and row["writing score"] >= 40 else "No", axis=1)

#dataset_copy["pass/fail"] = dataset_copy["average score"].apply(lambda z: "Yes" if z >= 50 else "No")
dataset_copy.head(20)

gender race/ethnicity parental level of education         lunch  \
0   female        group B           bachelor's degree      standard   
1   female        group C                some college      standard   
2   female        group B             master's degree      standard   
3     male        group A          associate's degree  free/reduced   
4     male        group C                some college      standard   
5   female        group B          associate's degree      standard   
6   female        group B                some college      standard   
7     male        group B                some college  free/reduced   
8     male        group D                 high school  free/reduced   
9   female        group B                 high school  free/reduced   
10    male        group C          associate's degree      standard   
11    male        group D          associate's degree      standard   
12  female        group B                 high school      standard   
13    male        group A                some college      standard   
14  female        group A             master's degree      standard   
15  female        group C            some high school      standard   
16    male        group C                 high school      standard   
17  female        group B            some high school  free/reduced   
18    male        group C             master's degree  free/reduced   
19  female        group C          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score pass/fail  
0                     none          72             72             74       Yes  
1                completed          69             90             88       Yes  
2                     none          90             95             93       Yes  
3                     none          47             57             44       Yes  
4                     none          76             78             75       Yes  
5                     none          71             83             78       Yes  
6                completed          88             95             92       Yes  
7                     none          40             43             39        No  
8                completed          64             64             67       Yes  
9                     none          38             60             50        No  
10                    none          58             54             52       Yes  
11                    none          40             52             43       Yes  
12                    none          65             81             73       Yes  
13               completed          78             72             70       Yes  
14                    none          50             53             58       Yes  
15                    none          69             75             78       Yes  
16                    none          88             89             86       Yes  
17                    none          18             32             28        No  
18               completed          46             42             46       Yes  
19                    none          54             58             61       Yes

### Assigning Independent variables to x & Dependent variables to y

In [74]:
x = dataset_copy.iloc[:, :-1].values
print(x)

[['female' 'group B' "bachelor's degree" ... 72 72 74]
 ['female' 'group C' 'some college' ... 69 90 88]
 ['female' 'group B' "master's degree" ... 90 95 93]
 ...
 ['female' 'group C' 'high school' ... 59 71 65]
 ['female' 'group D' 'some college' ... 68 78 77]
 ['female' 'group D' 'some college' ... 77 86 86]]


In [75]:
y = dataset_copy.iloc[:, -1].values
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'

### Encoding Independent variables

In [84]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 4])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

#print(pd.DataFrame(x))
print(x)

[[0.0 1.0 1.0 ... 72 72 74]
 [0.0 1.0 1.0 ... 69 90 88]
 [0.0 1.0 1.0 ... 90 95 93]
 ...
 [0.0 1.0 1.0 ... 59 71 65]
 [0.0 1.0 1.0 ... 68 78 77]
 [0.0 1.0 1.0 ... 77 86 86]]


### Encoding Dependent variables

In [86]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(pd.DataFrame(y))
#print(y)

     0
0    1
1    1
2    1
3    1
4    1
..  ..
995  1
996  1
997  1
998  1
999  1

[1000 rows x 1 columns]
